---
# tasks file for ansible-role-ansiboard
- name: directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ ansiboard_basedir }}"
    - "{{ ansiboard_basedir }}/groups"
    - "{{ ansiboard_basedir }}/hosts"

- name: render front page
  template:
    src: frontpage.html.j2
    dest: "{{ ansiboard_basedir }}/index.html"

- name: render individual group pages
  template:
    src: groupmembers.html.j2
    dest: "{{ ansiboard_basedir }}/groups/{{ item.key }}.html"
    owner: root
    group: root
  with_dict: "{{ groups }}"

- name: render host pages
  template:
    src: host.html.j2
    dest: "{{ ansiboard_basedir }}/hosts/{{ item.key }}.html"
    owner: root
    group: root
  with_dict: "{{ hostvars }}"
