---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for instance to be ready
      ansible.builtin.wait_for_connection:
        timeout: 120

    - name: Gather facts
      ansible.builtin.setup:

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - dbus
          - tzdata
        state: present
        update_cache: true
      when:
        - ansible_facts['os_family'] == "Debian"
