---
- name: Prepare
  hosts: all
  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - dbus
          - tzdata
        state: present
        update_cache: true
      when:
        - ansible_facts['os_family'] == "Debian"
